config/routes.rb
Rails.application.routes.draw do

  resources :snippets
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  

  root "snippets#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)

      alias_action :create, :read, :update, :destroy, :to => :crud

      can :crud, Snippet do |s|
        s.user == user && user.persisted?
      end

      can :private, Snippet do |s|
        (s.user == user && user.persisted?) || (s.user != user && s.private == false)
      end

    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :snippets, dependent: :nullify

  validates :kind, presence: true

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base

  belongs_to :category
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :work, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :snippets, dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in!" unless user_signed_in?
  end

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find session[:user_id] if user_signed_in?
  end
  helper_method :current_user

  def sign_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :redirect_if_loggedin, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Wrong credentials!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

  private

  def redirect_if_loggedin
    redirect_to root_path, notice: "Already logged in!" if user_signed_in?
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_snippet, only: [:show, :edit, :update, :destroy]
  before_action :authorize_snippet, only: [:edit, :update, :destroy]
  before_action :private_snippet, only: [:show]

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new snippet_params
    @snippet.user = current_user
    if @snippet.save
      redirect_to snippet_path(@snippet), notice: "Snippet created!"
    else
      flash.now[:alert] = "Snippet not created!"
      render :new
    end
  end

  def show
  end

  def index
    @categories = Category.order(:id)
  end

  def edit
  end

  def update
    if @snippet.update snippet_params
      redirect_to snippet_path(@snippet), notice: "Snippet updated!"
    else
      flash.now[:alert] = "Snippet not updated!"
      render :edit
    end
  end

  def destroy
    @snippet.destroy
    redirect_to snippets_path, notice: "Snippet deleted!"
  end

  private

  def private_snippet
    redirect_to root_path unless can? :private, @snippet
  end

  def authorize_snippet
    redirect_to root_path unless can? :crud, @snippet
  end

  def find_snippet
    @snippet = Snippet.find params[:id]
  end

  def snippet_params
    params.require(:snippet).permit(:category_id, :title, :work, :private)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Account created!"
    else
      flash.now[:alert] = "Account not created!"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
                                  :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Home", snippets_path %>
|
<%= link_to "Create snippet", new_snippet_path %>
<br>
<h1>Code Snippets</h1>
<div align="right">
  <% if user_signed_in? %>
    Hello, <%= current_user.first_name %>!
    |
    <%= link_to "Log out", sessions_path, method: :delete %>
  <% else %>
    <%= link_to "Log in", new_session_path %>
    |
    <%= link_to "Sign up", new_user_path %>
  <% end %>
</div>
<hr>

<%= notice || alert %>

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<% if @snippet.errors.any? %>
  <ul>
    <% @snippet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @snippet do |f|%>
  <div>
    <%= f.label :kind %>
    <%= f.collection_select :category_id, Category.order(:id), :id, :kind %>
  </div>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :work %>
    <%= f.text_area :work %>
  </div>
  <div>
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>
  <%= f.submit %>
<% end %>

app/views/snippets/edit.html.erb
<h1>Edit a Snippet</h1>

<%= render "form" %>

app/views/snippets/index.html.erb
<% @categories.each do |categ| %>
  <% @count = 0 %>
  <% categ.snippets.order(:id).each do |snip| %>
    <% if can? :private, snip  %>
      <% @count += 1 %>
    <% end %>
  <% end %>
  <h3><%= "#{categ.kind} (#{@count} Snippets)" %></h3>

  <ul>
    <% categ.snippets.order(:id).each do |snip| %>
      <% if snip.private %>
        <% @priv = "(private)" %>
      <% else %>
        <% @priv = "" %>
      <% end %>

      <% if can? :private, snip  %>
        <li><%= link_to "#{snip.title} #{@priv}", snippet_path(snip) %></li>
      <% end %>
    <% end %>
  </ul>
  <br>
<% end %>

app/views/snippets/new.html.erb
<h1>Create a Snippet</h1>

<%= render "form" %>

app/views/snippets/show.html.erb
<div>
  <h2>(<em><%= @snippet.category.kind %></em>)</h2>
</div>
<div>
  <% if @snippet.private %>
    <h3><strong>---Private---</strong></h3>
  <% else %>
    <h3><strong>---Public---</strong></h3>
  <% end %>
</div>
<div>
  <h2>Title:</h2>
  <%= @snippet.title %>
</div>
<br>
<div>
  <h2>Work:</h2>
  <%= markdown(@snippet.work) %>
  <%#= markdown("```" + @snippet.category.kind.downcase + "\n" + @snippet.work + "\n" + "```") %>
</div>
<br>

<% if can? :update, @snippet %>
  <%= link_to "Edit", edit_snippet_path(@snippet) %>
<% end %>

<% if can? :destroy, @snippet %>
  <%= link_to "Delete", snippet_path(@snippet),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
<% end %>

app/views/users/new.html.erb
<h1>Please enter your info</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Create an Account" %>
  </div>
<% end %>